### ISSUE TITLE
Honor play camera not work

### ISSUE THREAD

**Issue by cven95** [naz664/xdroid_gsi#1]
Camera not work in honor play with huawei kirin 970 chaps how can i solve this bugs ,but before that GSI image it work in the crdoid GSI and AncientOS but in this not work any solve for this problem please and thank for this good GSI image.

**Comment by naz664** [comment]
Yeah,
I got reports (few)
Since i already mentioned earlier in group. this was a test build, 
So haven't fully checked all stuffs.

**Comment by cven95** [comment]
Ok thanks it is beautiful GSI
